name: Code check

on:
  push: null
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  path-filter:
    timeout-minutes: 30
    outputs:
      actions: ${{steps.changes.outputs.actions}}
      deno: ${{steps.changes.outputs.deno}}
      karabiner: ${{steps.changes.outputs.karabiner}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            actions:
              - .github/workflows/*.yml
              - .github/workflows/*.yaml
              - .github/actions/*.yml
              - .github/actions/*.yaml
              - flake.nix
              - flake.lock
            renovate:
              - renovate.json5
              - flake.nix
              - flake.lock

  check-format:
    timeout-minutes: 5
    name: Check code format
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: setup nix
        uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
  check-actions:
    timeout-minutes: 5
    needs: path-filter
    if: needs.path-filter.outputs.actions == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: setup nix
        uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run .#check-actions
  check-renovate-config:
    timeout-minutes: 5
    needs: path-filter
    if: needs.path-filter.outputs.renovate == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: setup nix
        uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run .#check-renovate-config
  status-check:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs:
      - check-format
      - check-actions
      - check-renovate-config
    permissions: {}
    if: failure()
    steps:
      - run: exit 1
